config/routes.rb
Rails.application.routes.draw do
  get 'order_items/:id/add' => "order_items#add_quantity", as: "order_item_add"
  get 'order_items/:id/reduce' => "order_items#reduce_quantity", as: "order_item_reduce"
  post 'order_items' => "order_items#create"
  delete 'order_items/:id/delete' => "order_items#destroy", as: "order_item_destroy"
  get 'order_items/:id' => "order_items#show", as: "order_item"
  
  get 'cart' => "carts#show", as: "cart"
  delete 'cart_empty' => "carts#destroy"
  
  resources :orders, only: [:index, :show, :new]
  resources :products
  
  devise_for :users, skip: [:sessions]
  as :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    get 'register', to: 'devise/registrations#new', as: :register
    get 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :order_items, dependent: :destroy
  has_many :products, through: :order_items

  # LOGIC
  def sub_total
    sum = 0
    order_items.each do |line_item|
      sum += line_item.total_price
    end
    sum
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  # LOGIC
  def total_price
    quantity * product.price
  end
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# cart
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :current_cart

  private

  def current_cart
    if session[:cart_id].nil?
      @current_cart = Cart.create
    end
    @current_cart = Cart.find_by(id: session[:cart_id])
    if @current_cart.nil?
      @current_cart = Cart.create
    end
    session[:cart_id] = @current_cart.id
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = @current_cart
  end

  def destroy
    @current_cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end
end

app/controllers/home_controller.rb
# Root controller
class HomeController < ApplicationController
    def index; end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :fetch_current_product, only: [:create]
  before_action :fetch_order_item, only: %i[destroy add_quantity reduce_quantity]

  def create
    if @current_cart.products.include?(@chosen_product)
      @order_item = current_cart.order_items.find_by(product_id: @chosen_product)
      @order_item.quantity += 1
    else
      @order_item = OrderItem.new(quantity: 1)
      @order_item.cart = @current_cart
      @order_item.product = @chosen_product
    end
    @order_item.save
    redirect_to cart_path
  end

  def destroy
    @current_order_item.destroy
    redirect_to cart_path
  end

  def add_quantity
    @current_order_item.quantity += 1
    @current_order_item.save
    redirect_to cart_path
  end

  def reduce_quantity
    @current_order_item.quantity -= 1 if @current_order_item.quantity > 1
    @current_order_item.save
    redirect_to cart_path
  end

  private

  def fetch_order_item
    @current_order_item = OrderItem.find(params[:id])
  end

  def fetch_current_product
    @chosen_product = Product.find(params[:product_id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new({
      "name" => 'user1',
      "email" => 'user1@mail.com',
      "address" => 'user1 address',
      "pay_method" => 'Tarjet'
    })
    @current_cart.order_items.each do |item|
      @order.order_items << item
    end
    @order.save!
    #Cart.destroy(session[:cart_id])
    session[:cart_id] = nil
    redirect_to root_path
  end

  private

  def order_params
    params.require(:order).permit(:name, :email, :address, :pay_method)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :stock)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/carts/show.html.erb
<h1>Cart</h1>
<ul>
  <% @cart.order_items.each do |order_item| %>
    <li>Item: <%= order_item.product.name %>/ Price: <%= number_to_currency(order_item.product.price) %>/ Quantity: <%= order_item.quantity %>/ Total Price: <%= number_to_currency(order_item.total_price) %>
      <ul>
        <li>
          <%= link_to "Add 1", order_item_add_path(id: order_item), method: :post %>
        </li>
        <li>
          <%= link_to "Reduce 1", order_item_reduce_path(id: order_item), method: :post %>
        </li>
        <li>
          <%= button_to "Remove item", order_item_destroy_path(order_item),method: :delete %>
        </li>
      </ul>
    </li>
  <% end%>
</ul>
<h3>Sub total: <%= number_to_currency(@cart.sub_total) %></h3>
# See Order section below for explanation of new_order_path
<%= link_to "Proceed to checkout", new_order_path %><br>
#
<%= button_to "Empty cart", cart_empty_path,method: :delete, data: {confirm: "Are you sure?"}%>

app/views/home/index.html.erb
<h1>
  Home
</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ferreteriarb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body>
    <div>
      <% if signed_in? %>
        <%= link_to "Home", root_path%>
        <%= link_to "Products", products_path%>
        <%= link_to "Orders", orders_path%>
        <%= link_to "Cart", cart_path%>
        <%= link_to "Logout", destroy_user_session_path%>
      <% else %>
        <%= link_to "Register", register_path %>
        <%= link_to "Login", new_user_session_path %>
      <% end %>
    </div>
    <p class="alert" style="color: green"><%= notice %></p>
    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<h2>All Orders</h2>
<% @orders.each do |order| %>
  <p>Name: <%= order.name %></p>
  <p>Email: <%= order.email %></p>
  <p>Items: </p>
  <ul>
    <% order.order_items.each do |item| %>
      <li><%= item.quantity %> x <%= item.product.name %></li>
    <% end %>
  </ul>
<% end %>

app/views/orders/new.html.erb
<%= form_for(@order) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, required: true, autofocus: true %>
  </p>
  <p>
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </p>
  <p>
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :stock, style: "display: block" %>
    <%= form.number_field :stock %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Stock:</strong>
    <%= product.stock %>
  </p>

</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<h1>Products</h1>
<div id="products">
  <% @products.each do |product| %>
    <%= render product %>
    <p>
      <%= button_to "Add #{product.name} to cart", order_items_path(product_id: product.id) %>
      <%= link_to "Show this product", product %>
    </p>
  <% end %>
</div>
<%= link_to "New product", new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<%= render @product %>
<div>
  <%= button_to "Add #{@product.name} to cart", order_items_path(product_id: @product.id) %>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>
  <%= button_to "Destroy this product", @product, method: :delete %>
</div>